before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w
      - -X github.com/arrow2nd/jisyo/main.version={{.Version}}

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

brews:
  - name: jisyo
    repository:
      owner: arrow2nd
      name: homebrew-tap
      token: "{{ .Env.GORELEASER_GITHUB_TOKEN }}"
    url_template: "https://github.com/arrow2nd/jisyo/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    folder: Formula
    homepage: "https://arrow2nd.com/works/jisyo"
    description: "📚 SKK辞書マネージャ"
    license: "MIT"
    test: |
      system "#{bin}/jisyo -v"
    install: |
      bin.install "jisyo"

scoops:
  - repository:
      owner: arrow2nd
      name: scoop-bucket
      token: "{{ .Env.GORELEASER_GITHUB_TOKEN }}"
    url_template: "https://github.com/arrow2nd/jisyo/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    homepage: "https://arrow2nd.com/works/jisyo"
    description: "📚 SKK辞書マネージャ"
    license: "MIT"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^test:"
